<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="HeroIcons.Avalonia" Version="2.0.0" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.1.0-dev-292" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
        <PackageReference Include="Serilog" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\third_party\ShadUI\ShadUI\ShadUI.csproj" />
    </ItemGroup>

</Project>
