<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MicroClaw.Core\MicroClaw.Core.csproj" />
      <ProjectReference Include="..\MicroClaw.Pet\MicroClaw.Pet.csproj" />
      <ProjectReference Include="..\MicroClaw.Session\MicroClaw.Session.csproj" />
    </ItemGroup>

</Project>
