// <auto-generated />
using MicroClaw.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroClaw.Database.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    partial class GlobalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MicroClaw.Database.CallDailyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("CallCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("call_count");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<long>("FailCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fail_count");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success_count");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("DayNumber", "ProviderId", "SessionId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_token_daily_day_provider_session_source");

                    b.ToTable("call_daily", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Database.TokenDailyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<decimal>("CacheInputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_input_cost_usd");

                    b.Property<decimal>("CacheOutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_output_cost_usd");

                    b.Property<long>("CachedInputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cached_input_tokens");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<decimal>("InputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_cost_usd");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<decimal>("OutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_cost_usd");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("DayNumber", "ProviderId", "SessionId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_token_daily_day_provider_session_source");

                    b.ToTable("token_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
