providers:
- id: 2f26b5fa8b814668ab204aa69b9bb1b0
  display_name: MiniMax2.5
  protocol: openai
  base_url: https://api.minimaxi.com/v1
  api_key: xxx
  model_name: MiniMax-M2.5
  enabled: true
- id: 2f70ca1df35549c7925e388c08fe186c
  display_name: Test
  protocol: anthropic
  base_url: https://api.minimaxi.com/anthropic
  api_key: xxx
  model_name: MiniMax-M2.5
  enabled: true
