// <auto-generated />
using MicroClaw.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroClaw.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260328084810_AddAllowedSubAgentIds")]
    partial class AddAllowedSubAgentIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.AgentConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AllowedSubAgentIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContextWindowMessages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("context_window_messages");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisabledMcpServerIdsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_mcp_server_ids_json");

                    b.Property<string>("DisabledSkillIdsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_skill_ids_json");

                    b.Property<bool>("ExposeAsA2A")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("expose_as_a2a");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ToolGroupConfigsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_group_configs_json");

                    b.HasKey("Id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.ChannelConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("settings_json");

                    b.HasKey("Id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.ChannelRetryQueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_message");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<long>("NextRetryAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_retry_at_ms");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_retry_queue_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_channel_retry_queue_status");

                    b.ToTable("channel_retry_queue", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.CronJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<long?>("LastRunAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_run_at_ms");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<long?>("RunAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_at_ms");

                    b.Property<string>("TargetSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_session_id");

                    b.HasKey("Id");

                    b.ToTable("cron_jobs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.CronJobRunLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CronJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_job_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("TriggeredAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("triggered_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("CronJobId")
                        .HasDatabaseName("ix_cron_job_run_logs_cron_job_id");

                    b.ToTable("cron_job_run_logs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.McpServerConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArgsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("args_json");

                    b.Property<string>("Command")
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("EnvJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("env_json");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("headers_json");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport_type");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("mcp_server_configs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.ProviderConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxOutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(8192)
                        .HasColumnName("max_output_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.RagConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_rag_configs_scope");

                    b.ToTable("rag_configs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("ApprovalReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_reason");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_approved");

                    b.Property<string>("ParentSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_session_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.SkillConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.HasKey("Id");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.UsageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("CacheInputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_input_cost_usd");

                    b.Property<decimal>("CacheOutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_output_cost_usd");

                    b.Property<long>("CachedInputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("cached_input_tokens");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<decimal>("InputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_cost_usd");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<decimal>("OutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_cost_usd");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ProviderId", "Source", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_usages_session_provider_source_day");

                    b.ToTable("usages", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.WorkflowConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("DefaultProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_provider_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EdgesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("edges_json");

                    b.Property<string>("EntryNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_node_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NodesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("nodes_json");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_ms");

                    b.HasKey("Id");

                    b.ToTable("workflows", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
