// <auto-generated />
using MicroClaw.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroClaw.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260418084546_RemoveRagSearchStats")]
    partial class RemoveRagSearchStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.ChannelRetryQueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_type");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_message");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<long>("NextRetryAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_retry_at_ms");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_retry_queue_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_channel_retry_queue_status");

                    b.ToTable("channel_retry_queue", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.CronJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<long?>("LastRunAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_run_at_ms");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<long?>("RunAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_at_ms");

                    b.Property<string>("TargetSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_session_id");

                    b.HasKey("Id");

                    b.ToTable("cron_jobs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.CronJobRunLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CronJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_job_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("TriggeredAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("triggered_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("CronJobId")
                        .HasDatabaseName("ix_cron_job_run_logs_cron_job_id");

                    b.ToTable("cron_job_run_logs", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.Data.UsageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<decimal>("CacheInputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_input_cost_usd");

                    b.Property<decimal>("CacheOutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cache_output_cost_usd");

                    b.Property<long>("CachedInputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("cached_input_tokens");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<decimal>("InputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_cost_usd");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<decimal>("OutputCostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_cost_usd");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long>("UpdatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_ms");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "SessionId", "ProviderId", "Source", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_usages_agent_session_provider_source_day");

                    b.ToTable("usages", (string)null);
                });

            modelBuilder.Entity("MicroClaw.Infrastructure.PainMemoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AvoidanceStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("avoidance_strategy");

                    b.Property<string>("ConsequenceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("consequence_description");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_ms");

                    b.Property<long>("LastOccurredAtMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_occurred_at_ms");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurrence_count");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("severity");

                    b.Property<string>("TriggerDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_description");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_pain_memories_agent_id");

                    b.HasIndex("AgentId", "Severity")
                        .HasDatabaseName("ix_pain_memories_agent_severity");

                    b.ToTable("pain_memories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
